messages:
  general:
    hover-preview: "<aqua>将你的鼠标指针停留在该文本上，以预览这个物品."
    owner-info: "<gray>该物品展示框已被<0>保护."
  book:
    anonymous: "Anonymous"
    no-title: "No Title"
  frame:
    success-set: "<green>成功保护该物品展示框."
    success-remove: "<green>已成功移除该物品展示框的保护."
    failed-other-protected: "<red>保护该物品展示框失败 -- 这个物品展示框已经被<0>保护."
    failed-invalid: "<red>只能保护物品展示框!"
